services:
  bot:
    build: .
    container_name: si-bot

    environment:
      - DISCORD_TOKEN
      - LOG_CHANNEL_ID
      - OWNER_USER_ID
      - GUILD_ID
      - API_KEY_AI
      - OPENROUTER_MODEL
      - WELCOME_CHANNEL_ID
      - ROLE_BOYS_ID
      - ROLE_GIRLS_ID
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - IS_OWNER_INACTIVE

    restart: unless-stopped

    volumes:
      - /home/ubuntu/discord-bot/data:/app/data

    logging:
      options:
        max-size: "10m"
        max-file: "3"