services:
  bot:
    build: .
    container_name: si-bot
    environment:
      - DISCORD_TOKEN
      - LOG_CHANNEL_ID
      - OWNER_USER_ID
      - GUILD_ID
      - API_KEY_AI
      - OPENROUTER_MODEL
      - WELCOME_CHANNEL_ID
      - ROLE_BOYS_ID
      - ROLE_GIRLS_ID
    restart: unless-stopped
    volumes:
      - ./cookies.txt:/app/cookies.txt:ro
